### ISSUE TITLE
Configure fails if ngs-sdk is not made previously

### ISSUE THREAD

**Issue by yesimon** [ncbi/ngs#1]
Doing a clean ./configure from the source, the part configuring ngs-bam fails because it complains it cannot find ngs-sdk, which isn't made yet. So after ./configure bails, doing ```make -C ngs-sdk``` and then  reconfigure and make works. It would probably be better to handle this cleanly.

```
CONFIGURING ngs-bam
Configuring NGS-BAM package
checking system type... Linux
checking machine architecture... x86_64
checking NGS-BAM version... 1.1.0
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking for ngs-sdk package...
        includes... ../ngs-sdk
configure: error: required ngs-sdk package not found.
```

**Comment by agarwal** [comment]
I also get this error on an Ubuntu machine, but note it doesn't happen on Mac OS X. Unfortunately, I get a different error #6 on Mac, but I'm not sure there's any connection.

**Comment by kwrodarmer** [comment]
This happens for first time users, and is an issue we're aware of.

**Comment by dummey** [comment]
Can a comment linking to this ticket be added to: https://github.com/ncbi/ngs/wiki/Building-and-Installing-from-Source

**Comment by kwrodarmer** [comment]
done
