### ISSUE TITLE
configure script needs to be run in subdirectories

### ISSUE THREAD

**Issue by seandavi** [ncbi/ngs#13]
When using the top-level ./configure script, it appears that at least some of the subdirectory configure scripts are not being run.  So, I have to do:

``` sh
./configure
make -C ngs-sdk
make -C ngs-sdk install
make -C ngs-java
make -C ngs-java install
cd ngs-bam
./configure
cd ..
make -C ngs-bam
make -C ngs-bam install
```

Is this expected with a fresh git checkout from today?

**Comment by klymenko** [comment]
configure is executed in subdirectories

**Comment by seandavi** [comment]
Still missed one, I think. After I have run `./configure` in a top-level directory, I still see the following, but only for ngs-bam.

```
make -C ngs-bam/
*** File 'Makefile.config.mac.x86_64' is missing. Please run ./configure
make: *** [Makefile.config.mac.x86_64] Error 1
```

**Comment by klymenko** [comment]
ngs-bam is intentionally excluded.
In fact, it is a separate package.
It requires ncbi-vdb.

To build it, you need:
- configure and make ngs/ngs-sdk
- configure and make ncbi-vdb
Just now you can configure and make ngs/ngs-bam.

**Comment by seandavi** [comment]
Thanks, @klymenko. It is probably somewhere, but I did not see that documented in the building from source page here:

https://github.com/ncbi/ngs/wiki/Building-and-Installing-from-Source

No problem, but it did lead to my confusion.

**Comment by kwrodarmer** [comment]
We'll update documentation if it's not clear. Thanks, @seandavi !
