### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by oh-wo-dk** [ncbi/ngs#18]
Hello there,
Please excuse me if this question is answered somewhere else.

I am unsure what the API documentation looks like or whereabouts I might find it. Is there some place I can go to better understand what this package does? 

I had a look through the examples but didn't find a good answer there.

**Comment by kwrodarmer** [comment]
There is API documentation generated in the form of Javadocs when you build ngs. Take a look at that first to see if it helps.

**Comment by oh-wo-dk** [comment]
Ok, thanks very much.
