### ISSUE TITLE
Please don't assume that only macos uses clang

### ISSUE THREAD

**Issue by yurivict** [ncbi/ngs#22]
This line ```my $versionMin = '-mmacosx-version-min=10.6';``` adds the flag that BSD systems using clang don't understand. Please either remove it, or adjust it.

**Comment by kwrodarmer** [comment]
Please notice that if you are building for BSD, then you are creating a new port: we only have (and support) builds for Linux, Mac and Windows. You are more than welcome to build for BSD, but your demands give the impression that you think we support BSD, and we don't.

**Comment by yurivict** [comment]
This is a bug report, not a demand.

**Comment by kwrodarmer** [comment]
Perhaps I misunderstood. If you are trying to create a new port, we would be happy to talk with you and work with you, but we lack the ability to test changes under BSD.

**Comment by yurivict** [comment]
I am about to create a port for FreeBSD. There are a few patches that I added for the port to build.

One of them is this issue, I had to add this patch:
```
-    my $versionMin = '-mmacosx-version-min=10.6';
+    my $versionMin = '';
```

You might want to only use this key (```-mmacosx-version-min```) on MacOS. Currently it is used for clang in general.

**Comment by yurivict** [comment]
FYI: I've added the port: https://svnweb.freebsd.org/ports/head/biology/ngs-sdk/
It works, you don't need to verify anything.

Few patches can be upstreamed:
* This one with ```mmacosx-version-min``` which is MacOS-specific
* Library suffix (```lib64```) is platform-specific. BSDs don't add ```$BITS``` to ```lib```
* Soname is probably MacOS-specific.

**Comment by klymenko** [comment]
[ngs](https://github.com/ncbi/ngs) was moved into [sra-tools](https://github.com/ncbi/sra-tools).
Please check use of clang there.
