### ISSUE TITLE
Cannot build and install

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ncbi/ngs#25]
When making ncbi-vdb as per instructions, get his error:

/stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.y:86.1-6: error: invalid directive: ‘%param’
/stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.y:86.8-35: error: syntax error, unexpected {...}
make[3]: *** [/stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.c] Error 1
make[3]: Leaving directory `/stornext/HPCScratch/home/allnutt.t/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/obj/libs/klib'
make[2]: *** [compile] Error 2
make[2]: Leaving directory `/stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib'
make[1]: *** [klib] Error 2
make[1]: Leaving directory `/stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs'
make: *** [libs] Error 2

**Comment by kwrodarmer** [comment]
What version of bison do you have?

**Comment by theo-allnutt-bioinformatics** [comment]
Bison 2.7

**Comment by aboshkin** [comment]
Upgrading to Bison 3.* should help. However, bison should not be invoked when doing a full build, the build should use the source-controlled bison-generated file instead. I am going to create an internal ticket to fix this.

If upgrading Bison is not an option, try this quick fix:

git checkout /stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.c
touch /stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.c
re-run the build

**Comment by theo-allnutt-bioinformatics** [comment]
Gives me this error:

$git checkout /stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.c
fatal: Not a git repository (or any parent up to mount point /stornext/HPCScratch)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by theo-allnutt-bioinformatics** [comment]
Gives me this error:

$git checkout /stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb/libs/klib/json-grammar.c
fatal: Not a git repository (or any parent up to mount point /stornext/HPCScratch)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by durbrow** [comment]
cd /stornext/HPCScratch/home/allnutt.t/bin/ncbi/ncbi-vdb
git checkout libs/klib/json-grammar.c

If your current working directory is not inside a git repository, git does not know what the repository is.

**Comment by klymenko** [comment]
@theo-allnutt-bioinformatics , do you still have problems?

**Comment by theo-allnutt-bioinformatics** [comment]
It's a long time ago now, I think I just gave up.
