### ISSUE TITLE
Any document or tutorial ?

### ISSUE THREAD

**Issue by YdlNAU** [ncbi/ngs#26]
This is the official site , i look the examples dir. But it don't have any input string.
I really just want to know, how to use it ,any example data or tutorial ?

**Comment by kwrodarmer** [comment]
See https://github.com/ncbi/ngs/tree/master/ngs-sdk/examples .

**Comment by YdlNAU** [comment]
I have already see this before ask the question. This is still the codes that you need to understand how the codes work, I mean you need to take a lot of time to learn this repo. to know how it work.
There are even no input string for this examples. I use Java.

**Comment by klymenko** [comment]
You can find information about building and running examples in README file located in [tar archives](https://github.com/ncbi/ngs/wiki/Downloads).

Java examples are [here](https://github.com/ncbi/ngs/tree/master/ngs-java).

**Comment by klymenko** [comment]
Do you still need help?
