### ISSUE TITLE
Update bundled libraries to allow compiling with up-to-date C++ environments

### ISSUE THREAD

**Issue by taltman** [ncbi/ngs#32]
Currently bundled libraries were built with much older C++ compiler & libraries; so unable to use them for compiling new projects on recent versions of Linux.

See Issue #31 for more details.

@aboshkin

**Comment by aboshkin** [comment]
@taltman we updated the Linux tarballs with the binaries built by g++ 7.3, please verify that they work for you:
https://github.com/ncbi/ngs/wiki/Downloads

**Comment by klymenko** [comment]
@taltman, did you try to build with updated libraries?

**Comment by taltman** [comment]
Sorry for the belated reply. I ended up compiling the dependencies myself as instructed, and it worked fine. Thanks for updating the bundled libraries.
