### ISSUE TITLE
please add LICENSE file

### ISSUE THREAD

**Issue by agarwal** [ncbi/ngs#5]
I'm guessing it is the same as that of `sra-tools`, but it would be good to state it clearly in this repo. Thank you.

**Comment by kwrodarmer** [comment]
The ngs code base makes no use of 3rd party sources, and the license information is contained in every source file, making the LICENSE file redundant, but we can add it.

**Comment by agarwal** [comment]
Having it in every file is more comprehensive, and I'm sorry I missed that. I won't mind if you ignore this issue. On the other hand, I did expect to see a LICENSE file and maybe others would too.

**Comment by klymenko** [comment]
LICENSE was added.
