### ISSUE TITLE
Compilation fails with parallel make -j N

### ISSUE THREAD

**Issue by tseemann** [ncbi/ngs#7]
If you try a parallel make (eg. `make -j 8`) the build fails.

This indicates some of your dependency rules are broken.

**Comment by kwrodarmer** [comment]
We'll look at it, thanks.

Can you describe how you're using the ngs APIs?

**Comment by tseemann** [comment]
This is to build `sra-tools` from source, for the Brew package:
https://github.com/Homebrew/homebrew-science/blob/a1252b84b9e115adbf51b326080101bd9e63d89f/sratoolkit.rb

**Comment by kwrodarmer** [comment]
As a workaround, you can just run make without -j. You may notice that internally we recursively invoke make and use -j where applicable, especially in the ncbi-vdb project.

**Comment by tseemann** [comment]
Yes we de-parallelize the make for this package because of the bug, but it slows down the build a lot.
